[package]
name = "ConwayWgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.12.0"
winit = "0.27.5"
env_logger = "0.11.5"
pollster = "0.4.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
cgmath = "0.18"
rand = "0.8.5"